/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#75f999",
        "on-secondary-fixed-variant": "#005225",
        "on-primary": "#ffffff",
        "surface-container": "#eceef0",
        "error": "#ba1a1a",
        "primary-fixed": "#d6e3ff",
        "primary-container": "#005eb8",
        "tertiary-fixed-dim": "#fbbc2e",
        "secondary": "#006d33",
        "on-surface": "#191c1e",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#007236",
        "on-primary-fixed": "#001b3d",
        "on-primary-fixed-variant": "#00468c",
        "on-tertiary-fixed": "#261900",
        "on-tertiary-container": "#ffd481",
        "background": "#f7f9fb",
        "primary-fixed-dim": "#a9c7ff",
        "surface-variant": "#e0e3e5",
        "surface": "#f7f9fb",
        "on-tertiary-fixed-variant": "#5d4200",
        "on-surface-variant": "#424752",
        "surface-tint": "#005db6",
        "secondary-fixed-dim": "#5adf82",
        "tertiary-fixed": "#ffdea4",
        "tertiary": "#5e4300",
        "on-secondary-fixed": "#00210b",
        "inverse-surface": "#2d3133",
        "surface-bright": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "on-secondary": "#ffffff",
        "outline-variant": "#c2c6d4",
        "outline": "#727783",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-background": "#191c1e",
        "inverse-on-surface": "#eff1f3",
        "on-primary-container": "#c8daff",
        "tertiary-container": "#7c5900",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed": "#78fc9c",
        "primary": "#00478d",
        "surface-dim": "#d8dadc",
        "surface-container-low": "#f2f4f6",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#a9c7ff",
        "accent-pink": "#FF6B9D",
        "accent-pink-container": "#FFE4EC"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-sm": "8px",
        "container-padding-mobile": "16px",
        "stack-md": "16px",
        "gutter": "16px",
        "base": "4px",
        "stack-lg": "24px",
        "container-padding-desktop": "32px"
      },
      fontFamily: {
        "headline-lg": ["Be Vietnam Pro", "sans-serif"],
        "label-md": ["Be Vietnam Pro", "sans-serif"],
        "headline-md": ["Be Vietnam Pro", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "headline-sm": ["Be Vietnam Pro", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-lg": ["30px", { "lineHeight": "40px", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "data-mono": ["13px", { "lineHeight": "18px", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
